name: ModelEngineAutoTexture
version: '1.0-SNAPSHOT'
main: com.ronaldzav.modelEngineTextureAuto.ModelEngineTextureAuto
api-version: '1.21'
load: POSTWORLD
commands:
  meat:
    description: Comando principal de ModelEngineAutoTexture
    usage: /meat [reload|about]
    permission: meat.admin
    permission-message: No tienes permiso para usar este comando.
permissions:
  meat.admin:
    description: Permite usar los comandos de administración de ModelEngineAutoTexture
    default: op
